export const USER_LOG_IN = "USER_LOG_IN";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const DISPLAY_ALL_POSTS = "DISPLAY_ALL_POSTS";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FILTER_POSTS = "FILTER_POSTS";
export const CREATE_NEW_BLOG_POST = "CREATE_NEW_BLOG_POST";
export const CREATE_NEW_COMMENT = "CREATE_NEW_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";

export const CREATE_NEW_ACCOUNT = "CREATE_NEW_ACCOUNT";

export const UPDATE_ACCOUNT_INFORMATION = "UPDATE_ACCOUNT_INFORMATION";

export const FETCH_ALL_BLOGS = "FETCH_ALL_BLOGS";
export const SORT_BLOGS_BY_NAME = "SORT_BLOGS_BY_NAME";
export const SORT_BLOGS_BY_AUTHOR = "SORT_BLOGS_BY_AUTHOR";
export const SORT_BLOGS_BY_CREATION_DATE = "SORT_BLOGS_BY_CREATION_DATE";
