export const USER_LOG_IN = "USER_LOG_IN";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const DISPLAY_ALL_POSTS = "DISPLAY_ALL_POSTS";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FILTER_POSTS = "FILTER_POSTS";
export const CREATE_NEW_BLOG_POST = "CREATE_NEW_BLOG_POST";
export const CREATE_NEW_COMMENT = "CREATE_NEW_COMMENT";

export const CREATE_NEW_ACCOUNT = "CREATE_NEW_ACCOUNT";
